### ISSUE TITLE
 cv, view, assign are disabled

### ISSUE THREAD

**Issue by vkarakolis-epu** [QualiChain/fe#376]
On recruitment page list for user bob@qualichain.com and the job “new job to test the platform” there is only one candidate but the buttons cv, view, assign are disabled

**Comment by mmilaprat** [comment]
this is because there is a reported bug into the users API that returns forbidden when a recruiter asks for information about users that has an apply to their jobs

**Comment by sskalidakis** [comment]
This is because the job objects and the job application objects are never successfully passed in the QualiChain db, through RabbitMQ, because of inconsistency in the job_id. The Qualichain db uses integer ids , KBZ uses String ids. Because of that issue, there are also several visualizations related to the jobs that fail to be displayed. KBZ is looking into it, **since this is urgent**. 
@mehrbodKBZ , an idea would be to add a second job id (integer but also unique) which will be used for all NTUA's APIs. Is this possible?

**Comment by mehrbodKBZ** [comment]
> This is because the job objects and the job application objects are never successfully passed in the QualiChain db, through RabbitMQ, because of inconsistency in the job_id. The Qualichain db uses integer ids , KBZ uses String ids. Because of that issue, there are also several visualizations related to the jobs that fail to be displayed. KBZ is looking into it, **since this is urgent**.
> @mehrbodKBZ , an idea would be to add a second job id (integer but also unique) which will be used for all NTUA's APIs. Is this possible?

We do not need a second ID if we can create unique integer IDs. The String type comes from UUID. probably a random number generator or a simple service from your side that returns the biggest existing ID+1 can help to replace UUIDs with integer. SI it Feasible for you?

**Comment by sskalidakis** [comment]
I totally agree with this approach . This solution has already been deployed. There are two new APIs that allow getting the largest existing job id +1 and job application id +1.

For the jobs:
GET /getlastjobid HTTP/1.1
Host: qualichain.epu.ntua.gr:5004

For the job applications:
qualichain.epu.ntua.gr:5004/getlastjobapplicationid

@mmilaprat please call these APIs from the frontend each time a job or a job application is created to get the id. Add this id to the json that you provide to KBZ. Please use "id" as the name of this parameter in your json objects. This change needs to be applied in both Job creation and JobApplication creation.

**Comment by mmilaprat** [comment]
I disagree, in my opinion it must be the jobs API who must recover these ids from NTUAs API when it receives a new POST and the received data is valid.

**Comment by mehrbodKBZ** [comment]
since there might be parallel calls to the API and the ID doesn't remain valid, It is better to do it from FE to have the id inside the data related to the id

**Comment by mmilaprat** [comment]
I desagree with thhis approach, I see several  posible problems like:

- if 2 recruiters create 2 jobs at the same time, is possible that they obtain the same jobId. 
- Another issue is that probalby we cannot do jobs migrations easily using the jobs API.
- What happens if the job with higher jobid is deleted, and later a new job is created, it will rehuse the jobid of the deleted job?

Anyway, after do the first test following this appoach, I was able to create a new job with the id = 5998 (that was the id I get from getlastjobid) , but if I use again the getlastjobid it still returns the value 5998, it must returns 5999, no?

Another issue, the job has been created because If I try to create it again I receive

Job Posting already exists, either delete Job with Job URI: :5998 or use update service

but it doesn't appears into the GET method of jobs API, by id yes (/jobs/5998)

**Comment by sskalidakis** [comment]
I agree with your first point @mmilaprat .I made a change in the code in order to use the database sequence to ensure that every id returned is unique, even if two users create jobs simultaneously . This sequence always increments, so even if you delete a job , there is no issue. From now on, every time someone tries to create a job (or a job application )  the id will be different (even if the creation fails). Since the new sequence starts from zero in both jobs and job applications, I deleted all the created jobs and job applications in our database to avoid future conflict (anyway they were not that many since most of the created jsobs and job apps never reached our database due to errors with the ids). The change is deployed.

The job you created in your example never reached our database (that is why the counter was stuck). I saw this error in the logs.
-2021-04-28 07:33:31,944 - workers.data_handler - INFO - Specialization : None does not exists (which means that in one of the request the specialisation was not provided. Thus, the job was never created. If this comes from the frontend, please do not allow empty specialisation fields when creating a job. If not, then probably @mehrbodKBZ  you should check along with Joao that the producer provides the specialisation)

**Comment by mmilaprat** [comment]
the specialization filed is mandatory into the FE, it seends this data

the data that the jobs API returns from job id = 5998 is

{"label":"to test last job id","comment":null,"creator_id":":19","jobDescription":"to test last job id","specialization":"Devops Engineer","contractType":"part_time","sector":null,"occupation":null,"listingOrganization":null,"hiringOrganization":null,"jobLocation":"","country":null,"state":null,"city":null,"startDate":"2020-12-31T23:00:00.000Z","endDate":"2021-12-30T23:00:00.000Z","seniorityLevel":"executive","expectedSalary":null,"salaryCurrency":null,"uri":":5998","id":"5998","skillReq":[],"workExperienceReq":[],"coursesReq":[],"educationReq":[]}


"specialization":"Devops Engineer"

**Comment by mmilaprat** [comment]
I tried again, with this json

{"startDate":"2021-04-19T22:00:00.000Z","endDate":"2021-05-09T22:00:00.000Z","label":"title New job to teest new JobId","jobDescription":"description New job to teest new JobId","jobLocation":"Location1","contractType":"volunteer","seniorityLevel":"entry_level","skillReq":[{"label":"Blockchain","proficiencyLevel":"expert","skillURI":":Skill_8","priorityLevel":"medium"}],"workExperienceReq":[{"label":"","position":"position experience 1","duration":"","comment":"description experience 1"}],"educationReq":[{"label":"title degree1","description":"description degree1"}],"specialization":"Data Engineer","hiringOrganization":"ASEP","country":"Country1","state":"State1","city":"City1","creator_id":":19","id":9}

and the response is:

Job Posting already exists, either delete Job with Job URI: :9 or use update service

**Comment by mmilaprat** [comment]
I incremented manually (f5 lot of times) the lastjobid until get the value 63

Then I did this POST

{"startDate":"2021-01-02T23:00:00.000Z","endDate":"2021-12-30T23:00:00.000Z","label":"title new job to test new job id","jobDescription":"description  new job to test new job id","jobLocation":"locationData","contractType":"full_time","seniorityLevel":"entry_level","skillReq":[{"label":"","proficiencyLevel":"advanced","skillURI":":Skill_6","priorityLevel":"medium"}],"workExperienceReq":[{"label":"","position":"position exp 1","duration":"","comment":"desc. exp 1"}],"educationReq":[{"label":"title degree 1","description":"desc. degree 1"}],"specialization":"Devops Engineer","hiringOrganization":"ASEP","creator_id":":19","country":"España","state":"Barcelona","city":"Martorelles","id":64}

The Job API response:

Status Code: 200 OK
Data:
@prefix qc:    <http://w3id.org/qualichain> .
@prefix cv:    <http://rdfs.org/resume-rdf/cv.rdfs> .
@prefix saro:  <https://w3id.org/saro> .

But the new job doesn't appers into the Jobs list, probably KBZ API has some problem with the Specialization field

**Comment by sskalidakis** [comment]
Yes, I saw all of them. Probably, you are correct. The first attempts must have failed because there were objects with the same id in the KBZ storage.
For each attempt you made and reached our system, though, I keep seeing the  same error :
2021-04-28 09:41:22,349 - workers.data_handler - INFO - Specialization : None does not exists

which means that this info is not provided in our consumer. Please, @mehrbodKBZ and @jff check this one.

**Comment by mmilaprat** [comment]
the MR #388 adds the id each time a job or a job application is created. But the issue between KBZ API and NTUA API is still pending

**Comment by mmilaprat** [comment]
@mehrbodKBZ , @sskalidakis did you find why the Specialization is empty in the syncronization process between dbs?

**Comment by mehrbodKBZ** [comment]
should be some old empty values on previous dummy data. WE will clean database

**Comment by mmilaprat** [comment]
if I'm not wrong, this error appears when a new POST (with valid data) is received by the Job API and it sends the data to NTUA to synchronize it (by RabbitMQ?), I don't know if previous dummy data can be the problem.

**Comment by mehrbodKBZ** [comment]
I did some updates, please check if it resolved

**Comment by mmilaprat** [comment]
I did a test and the new Job doesn't appear into the list, nut by Id it exists.

The data I posted was:


{"startDate":"2020-12-31T23:00:00.000Z","endDate":"2021-12-30T23:00:00.000Z","label":"New job 03/05/2021","jobDescription":"desc New job 03/05/2021","jobLocation":"loc","contractType":"volunteer","seniorityLevel":"executive","skillReq":[{"label":"Angular","proficiencyLevel":"intermediate","skillURI":"saro:Skill_6","priorityLevel":"medium"},{"label":"Blockchain","proficiencyLevel":"advanced","skillURI":"saro:Skill_8","priorityLevel":"medium"}],"workExperienceReq":[{"label":"","position":"pos1","duration":"","comment":"exp1"}],"educationReq":[{"label":"degree1","description":"desc degree 1"}],"specialization":"Devops Engineer","hiringOrganization":"ASEP","country":"country","state":"state","city":"city","creator_id":":19","id":68}

The API reponse was:

@prefix qc:    <http://w3id.org/qualichain> .
@prefix cv:    <http://rdfs.org/resume-rdf/cv.rdfs> .
@prefix saro:  <https://w3id.org/saro> .

**Comment by sskalidakis** [comment]
All of the inconsistencies in the schemas and the ids have been resolved. Now, jobs, cvs and job applications are created successfully in both storages. There are still a few steps till we conclude this one.
a)Editing an existing cv or job (and update the respective NTUA object)
b)Deleting an existing cv, job or job application (delete the objects from the NTUA storage as well)

We will share our DELETE APIs with KBZ to be called when an object is deleted and we will propose a way to handle the editing of objects in the following days.

**Comment by kapsali29** [comment]
Hi all, regarding the DELETE and UPDATE functionalities we need to consider also the data (Job, CV, Job application) existing in NTUA's database. So we propose KBZ (@mehrbodKBZ @jff ) add the following to add a field on json payloads that are produced to Rabbitmq called status and have 3 values for this field "create", "update", "delete". So using that field we will be able to do the respective actions. For instance

```
{'cv': ${cv}, 'status': "create/update/delete"}
{'job': ${job}, 'status': "create/update/delete"}
{'job_application': ${job_application}, 'status': "create/update/delete"}
```

**Comment by mmilaprat** [comment]
Hi, there is any new about this issue?
I tried and the authorization issue still there.

I did an apply for a job for the user 63 into the job 95
With the user 19 (recruiter of this job) view data of the job, but he still getting the 401 UNAUTHORIZED  from the API (/users/<userId>)
{
    "message": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."
}

**Comment by mmilaprat** [comment]
@sskalidakis @mehrbodKBZ , this issue can be closed?
